In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('annual_summary_2025.csv')

In [3]:
df1= pd.read_csv('monthly_summary_2025.csv')

In [4]:
df

,nationalGridBmUnit,PNLevel,MELLevel,MILLevel,BidVolume,OfferVolume,Metered,ExpectOT,CapacityCalibrated,NetError,ABSError,max_M_ABS_NetError%,installedCapacity_mwh,Fuel_type,A_NetError%,A_ABS_NetError%,Rank_A_ABS_NetError%,PctRank_A_ABS_NetError%
0,ABERU-1,3738.72,246455.20,0.00,0.0,0.0,1667.14,3231.40,-81245.58,1564.72,1692.16,4.13,NaN,OCGT,-1.93,1.93,945.0,0.65
1,ABRBO-1,249114.51,849720.00,0.00,0.0,0.0,247911.00,249114.51,667110.00,1203.54,61252.86,2.28,49.5,WIND,0.18,0.18,480.0,0.33
2,ABRTW-1,186973.00,608205.86,0.00,0.0,0.0,171932.92,186961.50,528504.86,15027.86,60861.14,21.57,18.0,WIND,2.84,2.84,1047.0,0.72
3,ACHLW-1,0.00,0.00,0.00,0.0,0.0,27831.05,0.00,79106.14,-27831.05,27831.05,52.37,NaN,WIND,-35.18,35.18,1376.0,0.95
4,ACHRW-1,204129.00,631081.32,0.00,0.0,0.0,158982.72,203360.46,625809.32,44377.70,82458.74,28.82,21.5,WIND,7.09,7.09,1225.0,0.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444,WNCRB-1,-3167.78,9657.44,-15470.51,0.0,0.0,-864.14,-1683.27,-1058.87,-818.53,1420.95,77.30,5.0,BATTERY,77.30,77.30,1411.0,0.97
1445,WTMSO-1,844371.50,1751389.75,0.00,0.0,0.0,853154.13,844339.30,1620976.95,-8814.83,132103.19,2.40,105.0,WIND,-0.54,0.54,685.0,0.47
1446,WTRLN-1,8991.50,223922.14,0.00,0.0,0.0,7485.92,8967.38,-69861.12,1480.50,2059.22,3.25,NaN,GAS,-2.12,2.12,974.0,0.67
1447,WTRSB-1,-4964.96,147233.10,-119512.32,0.0,0.0,-8741.96,-6295.24,-65366.70,2444.99,6243.81,7.73,NaN,BATTERY,-3.74,3.74,1114.0,0.77
1448,ZEN02A,-55105.27,173219.36,-209002.64,0.0,0.0,-11974.32,-6192.21,-71166.89,5774.15,18357.01,73.76,NaN,BATTERY,-8.11,8.11,1240.0,0.86

In [5]:
fuel_type_mapping = {
    'AG-ASTK99': 'AGGREGATED',
    'AG-BSTK99': 'AGGREGATED',
    'AG-DSTK99': 'AGGREGATED',
    'AG-ESTK06': 'AGGREGATED',
    'AG-ESTK99': 'AGGREGATED',
    'AG-FSTK99': 'AGGREGATED',
    'AG-JSTK99': 'AGGREGATED',
    'AG-LEDG02': 'AGGREGATED',
    'AG-LSTK05': 'AGGREGATED',
    'AG-LSTK99': 'AGGREGATED',
    'CMSTW-2': 'WIND',
    'IBD-ARTH1': 'INTERCONNECTOR',
    'IVD-ARTH1': 'INTERCONNECTOR',
    'KILSD-1': 'BATTERY',
    'KILSD-2': 'BATTERY',
    'KILSD-3': 'BATTERY',
    'KILSD-4': 'BATTERY',
    'PGPET-1': 'DIESEL'
}

In [6]:
def update_fuel_type(df):
    for bmu, fuel in fuel_type_mapping.items():
        df.loc[
            (df['nationalGridBmUnit'] == bmu) & (df['Fuel_type'] == 'NAN'),
            'Fuel_type'
        ] = fuel
    return df

In [7]:
# Update both DataFrames
df = update_fuel_type(df)
df1 = update_fuel_type(df1)

In [8]:
df

,nationalGridBmUnit,PNLevel,MELLevel,MILLevel,BidVolume,OfferVolume,Metered,ExpectOT,CapacityCalibrated,NetError,ABSError,max_M_ABS_NetError%,installedCapacity_mwh,Fuel_type,A_NetError%,A_ABS_NetError%,Rank_A_ABS_NetError%,PctRank_A_ABS_NetError%
0,ABERU-1,3952.24,248132.34,0.00,-74.88,903.06,2593.34,4266.48,-79747.44,1673.48,1816.40,5.76,NaN,OCGT,-2.10,2.10,967.0,0.67
1,ABRBO-1,249114.51,849720.00,0.00,0.00,0.00,247911.00,249114.51,667110.00,1203.54,61252.86,2.28,49.5,WIND,0.18,0.18,477.0,0.33
2,ABRTW-1,192626.00,615836.36,0.00,-4857.64,0.00,172731.14,187756.84,531183.36,15024.88,61204.12,21.13,18.0,WIND,2.83,2.83,1039.0,0.72
3,ACHLW-1,0.00,0.00,0.00,0.00,0.00,27831.05,0.00,79106.14,-27831.05,27831.05,52.37,NaN,WIND,-35.18,35.18,1370.0,0.95
4,ACHRW-1,206563.50,634759.32,0.00,-2092.92,0.00,159316.10,203702.04,627257.32,44385.94,82670.86,28.83,21.5,WIND,7.08,7.08,1214.0,0.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444,WNCRB-1,-3373.48,10245.15,-16694.82,-15.38,195.40,-821.14,-1684.73,-775.06,-862.95,1500.01,100.00,5.0,BATTERY,100.00,100.00,1438.0,0.99
1445,WTMSO-1,844371.50,1751389.75,0.00,0.00,0.00,853154.13,844339.30,1620976.95,-8814.83,132103.19,2.40,105.0,WIND,-0.54,0.54,689.0,0.48
1446,WTRLN-1,9778.76,231088.36,0.00,-487.04,4243.24,11843.08,13505.44,-63630.90,1661.36,2361.00,5.27,NaN,GAS,-2.61,2.61,1022.0,0.71
1447,WTRSB-1,-22243.08,315138.70,-283075.97,-20197.45,42240.20,-6200.69,-3055.76,-68662.14,3143.41,9440.21,12.50,NaN,BATTERY,-4.58,4.58,1136.0,0.78
1448,ZEN02A,-69042.61,196633.74,-254810.74,-1655.28,8887.16,-10778.57,-4033.54,-68850.19,6735.51,21552.93,100.00,NaN,BATTERY,-9.78,9.78,1250.0,0.86

In [8]:
df.to_csv('annual_summary_2025.csv', index= False)

In [9]:
df1.to_csv('monthly_summary_2025.csv', index=False)